var az_json = 
[
    {
        id : '1',
        card_id : '123',
        card_name : '',
        code_id : 'CHA2TN0001',
        code_name : '',
        list_id : '',
        list_name : '',
        area_code : '',
        area : 'Ао Йон',
        address : '7/12, Moo 4, Soi Pa Sak 3, Baandon-Cherngtalay Rd, T. Cherngtalay, Talang, Phuket, Thailand',
        type : 'House',
        stars : '5',
        name1 : 'Дом 2 спальни с общим бассейном',
        name1_en : 'Название 1 en',
        name2 : 'Дом 2 спальни с общим бассейном2',
        name2_en : 'Название 2 en',
        bedrooms : '2',
        bathrooms : '1',
        guests : '4',
        livingsize : '234',
        propertysize : '232',
        pool : 'S',
        tobeach : '3.5 km',
        seaview : 'N',
        parking : 'Y',
        security : 'N',
        cleaning : 'По запросу',
        changetowels : 'Гости заменяют сами по желанию',
        laundry : 'Стиральная машина',
        cpayments : 'Электроэнергия 5 бат/кВт',
        cleaning_en : 'Уборка en',
        changetowels_en : 'Замена белья en',
        loundry_en : 'Стирка en',
        cpayments_en : 'Коммунальные платежи en',
        date_reg : '22-10-2016',
        date_check : '22-10-2016',
        rating : '8.65',
        gps : '8.001441,98.309196',
        descr : 'Уютный 2 спальный дом район Банг Тао <br>Комфортный комплекс неподалеку от пляжа Банг Тао, находится в тихом уютном месте, состоит из 6 домов и одного общего бассейна. К пляжу 3.5 км, этот вариант отлично подойдет для гостей на транспорте.',
        descr_en : 'Описание en',
        descr_internal : 'Контакты: +66833909460 Максим менеджер',
        contacts : 'Контакты',
        price_day : '18000',
        price_week : '300000',
        price_month : '16000',
        price_longterm : '15000',
        price_sale : '25000',
        price_spec : '250000',
        img : 'http://www.kvartal.ru/img/showcase/39563387120_prv_7147862-S1-0015.jpg',
        gallery : [
                    'http://rating35.ru/wp-content/uploads/2014/09/ocenka-kvartir.jpg',
                    'http://www.avrealty.ru/images/today.jpg',
                    'http://mydesigninfo.ru/wp-content/uploads/2015/12/1442451505sdf.jpg'
                  ]
    },
    {
        id : '2',
        card_id : '123',
        card_name : '',
        code_id : 'CHA2TN0002',
        code_name : '',
        list_id : '',
        list_name : '',
        area_code : '',
        area : 'Банана',
        address : '7/12, Moo 4, Soi Pa Sak 3, Baandon-Cherngtalay Rd, T. Cherngtalay, Talang, Phuket, Thailand',
        type : 'House',
        stars : '3',
        name1 : '',
        name1_en : 'Название 1 en',
        name2 : 'Дом 2 спальни с общим бассейном2',
        name2_en : 'Название 2 en',
        bedrooms : '2',
        bathrooms : '1',
        guests : '4',
        livingsize : '234',
        propertysize : '232',
        pool : 'S',
        tobeach : '3.5 km',
        seaview : 'N',
        parking : 'Y',
        security : 'N',
        cleaning : 'По запросу',
        changetowels : 'Гости заменяют сами по желанию',
        laundry : 'Стиральная машина',
        cpayments : 'Электроэнергия 5 бат/кВт',
        cleaning_en : 'Уборка en',
        changetowels_en : 'Замена белья en',
        loundry_en : 'Стирка en',
        cpayments_en : 'Коммунальные платежи en',
        date_reg : '22-10-2016',
        date_check : '28-10-2016',
        rating : '8.65',
        gps : '8.001441,98.309196',
        descr : 'Уютный 2 спальный дом район Банг Тао <br>Комфортный комплекс неподалеку от пляжа Банг Тао, находится в тихом уютном месте, состоит из 6 домов и одного общего бассейна. К пляжу 3.5 км, этот вариант отлично подойдет для гостей на транспорте.',
        descr_en : 'Описание en',
        descr_internal : 'Контакты: +66833909460 Максим менеджер',
        contacts : 'Контакты',
        price_day : '20000',
        price_week : '310000',
        price_month : '10000',
        price_longterm : '19000',
        price_sale : '29000',
        price_spec : '//',
        img : 'http://ngloriya.su/userfiles/images/kvartiry-velikom-novgorode-2-big.jpg',
        gallery : [
                    'http://interiorizm.com/wp-content/uploads/2013/01/kvartira-v-odesse-02.jpg',
                    'http://www.artihome.ru/img/gal12/maxi/1.jpg',
                    'http://www.schelhotel.ru/images/stories/foto/1-12-1.jpg',
                    'http://kvartirka.com/netcat_files/thumbs/flat/0/132/132815/662019_w468h312.jpg'
                  ]
    }
];
// alert(az_json[1].gallery);
