var az_json = 
[
    {
        id : '1',
        card_id : '123',
        card_name : '',
        code_id : 'CHA2TN0001',
        code_name : '',
        list_id : '',
        list_name : '',
        area_code : '',
        area : 'Ао Йон',
        address : '7/12, Moo 4, Soi Pa Sak 3, Baandon-Cherngtalay Rd, T. Cherngtalay, Talang, Phuket, Thailand',
        type : 'House',
        stars : '5',
        name1 : 'Дом 2 спальни с общим бассейном',
        name1_en : 'Название 1 en',
        name2 : 'Дом 2 спальни с общим бассейном2',
        name2_en : 'Название 2 en',
        bedrooms : '2',
        bathrooms : '1',
        guests : '4',
        livingsize : '234',
        propertysize : '232',
        pool : 'S',
        tobeach : '3.5 km',
        seaview : 'N',
        parking : 'Y',
        security : 'N',
        cleaning : 'По запросу',
        changetowels : 'Гости заменяют сами по желанию',
        laundry : 'Стиральная машина',
        cpayments : 'Электроэнергия 5 бат/кВт',
        cleaning_en : 'Уборка en',
        changetowels_en : 'Замена белья en',
        loundry_en : 'Стирка en',
        cpayments_en : 'Коммунальные платежи en',
        date_reg : '22-10-2016',
        date_check : '22-10-2016',
        rating : '8.65',
        gps : '8.001441,98.309196',
        descr : 'Уютный 2 спальный дом район Банг Тао <br>Комфортный комплекс неподалеку от пляжа Банг Тао, находится в тихом уютном месте, состоит из 6 домов и одного общего бассейна. К пляжу 3.5 км, этот вариант отлично подойдет для гостей на транспорте.',
        descr_en : 'Описание en',
        descr_internal : 'Контакты: +66833909460 Максим менеджер',
        contacts : 'Контакты',
        price_day : '//',
        price_week : '//',
        price_month : '16000/18000/22000',
        price_longterm : '15000',
        price_sale : '',
        price_spec : '//',
        img : 'http://www.kvartal.ru/img/showcase/39563387120_prv_7147862-S1-0015.jpg'
    },
    {
        id : '2',
        card_id : '123',
        card_name : '',
        code_id : 'CHA2TN0002',
        code_name : '',
        list_id : '',
        list_name : '',
        area_code : '',
        area : 'Банана',
        address : '7/12, Moo 4, Soi Pa Sak 3, Baandon-Cherngtalay Rd, T. Cherngtalay, Talang, Phuket, Thailand',
        type : 'House',
        stars : '3',
        name1 : '',
        name1_en : 'Название 1 en',
        name2 : 'Дом 2 спальни с общим бассейном2',
        name2_en : 'Название 2 en',
        bedrooms : '2',
        bathrooms : '1',
        guests : '4',
        livingsize : '234',
        propertysize : '232',
        pool : 'S',
        tobeach : '3.5 km',
        seaview : 'N',
        parking : 'Y',
        security : 'N',
        cleaning : 'По запросу',
        changetowels : 'Гости заменяют сами по желанию',
        laundry : 'Стиральная машина',
        cpayments : 'Электроэнергия 5 бат/кВт',
        cleaning_en : 'Уборка en',
        changetowels_en : 'Замена белья en',
        loundry_en : 'Стирка en',
        cpayments_en : 'Коммунальные платежи en',
        date_reg : '22-10-2016',
        date_check : '22-10-2016',
        rating : '8.65',
        gps : '8.001441,98.309196',
        descr : 'Уютный 2 спальный дом район Банг Тао <br>Комфортный комплекс неподалеку от пляжа Банг Тао, находится в тихом уютном месте, состоит из 6 домов и одного общего бассейна. К пляжу 3.5 км, этот вариант отлично подойдет для гостей на транспорте.',
        descr_en : 'Описание en',
        descr_internal : 'Контакты: +66833909460 Максим менеджер',
        contacts : 'Контакты',
        price_day : '//',
        price_week : '//',
        price_month : '16000/18000/22000',
        price_longterm : '15000',
        price_sale : '',
        price_spec : '//',
        img : 'http://ngloriya.su/userfiles/images/kvartiry-velikom-novgorode-2-big.jpg'
    }
];
